# Generated by Django 5.2.6 on 2025-09-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image_url',
            new_name='image',
        ),
    ]
