# Generated by Django 5.2.6 on 2026-03-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0010_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrating',
            old_name='total_revuews',
            new_name='total_reviews',
        ),
    ]
