# Generated by Django 5.2.6 on 2026-04-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0011_rename_total_revuews_productrating_total_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
